---
title: "Untitled"
author: "Cole B. Brookson"
date: "`r Sys.Date()`"
output: html_document
---

```{css, echo=FALSE}
.small-source, .small-output, .small-warning, .small-error, .small-message {
  width: calc(70% - 2em);
  height: auto;
}
```


```{r setup}
library(knitr)
library(here)

knitr::opts_chunk$set(class.source = "small-source", 
                      class.output = "small-output", 
                      class.warning = "small-warning",
                      class.error = "small-error",
                      class.message = "small-message")
```

```{r}
library(knitr)
library(here)



# 00 section ===================================================================
files_00 <- list.files(here("./content/html/getting-started/"), "\\.rhtml")
for (f in files_00)
  knit(paste0(here("./content/html/getting-started/"), f), 
       sub("\\.rhtml$", ".html", 
           paste0(here("./content/html/getting-started/"), f)), envir = new.env())

# 01 section ===================================================================
files_01 <- list.files(here("./content/html/basic-r/"), "\\.rhtml")
for (f in files_01)
  knit(paste0(here("./content/html/basic-r/"), f), 
       sub("\\.rhtml$", ".html", 
           paste0(here("./content/html/basic-r/"), f)), envir = new.env())

# 02 section ===================================================================
files_02 <- list.files(here("./content/html/working-with-data/"), "\\.rhtml")
for (f in files_02)
  knit(paste0(here("./content/html/working-with-data/"), f), 
       sub("\\.rhtml$", ".html", 
           paste0(here("./content/html/working-with-data/"), f)), envir = new.env())

# 03 section ===================================================================
files_03 <- list.files(here("./content/html/plotting/"), "\\.rhtml")
for (f in files_03)
  knit(paste0(here("./content/html/plotting/"), f), 
       sub("\\.rhtml$", ".html", 
           paste0(here("./content/html/plotting/"), f)), envir = new.env())

# 04 section ===================================================================
files_04 <- list.files(here("./content/html/stats/"), "\\.rhtml")
for (f in files_04)
  knit(paste0(here("./content/html/stats/"), f), 
       sub("\\.rhtml$", ".html", 
           paste0(here("./content/html/stats/"), f)))
```

