---
output:
  pdf_document: default
  html_document: default
---
# Introduction to Basic Statistics
**Author:** Cole Brookson
**Date:** 29 August 2022

The goal of this section is to provide students with a central resource to refer to with their programming/statistics questions as far as they relate to their undergraduate courses in the EEB department at UofT. To this end, this section is meant to help students become more familiar and comfortable with simple statistical tests and also with more complex statistical models. Hopefully this set of resources acts to help students develop an *intuitive understanding* of the material, and not just simply memorize the content. 

We generally advise that if you are using this section as a primary learning resource (i.e. you are coming here for knowledge on a topic, not to troubleshoot), that you follow the order laid out here somewhat. 

It is typically better to first understand the principles of <a href="./04-01-probability-101.html">Probability</a> and <a href="./04-03-sampling-distributions.html">Sampling</a> before you move on to questions about <a href="./04-08-linear-regression.html">Regression</a>. 

In addition, we understand that there is no way we can do justice to the entire conversation of <a href="./04-04-hypothesis-testing.html">hypothesis testing</a> in a short article like this. However, we <strong>strongly</strong> recommend you read through that section to get an idea about significance testing for hypotheses before you actually <em>perform</em> any tests. 