
# Software Downloads
**Author:** Cole Brookson
**Date:** 25 June 2022

To use the programming language R, you need to have both the R software downloaded, as well as a way to interact with that software. We will use the integrated development environment (IDE) RStudio for this task. To install the required softwares on your computer, please follow the instructors according to your operating system. 

#### Windows

You will need to download R and RStudio separately. 

##### R

* First, follow the instructions to download R from the [CRAN website](https://cran.r-project.org/bin/windows/base/) for the most recent version. **For Fall 2022, we will expect you to be using R-4.2.1**
* Run the `.exe` file that was just downloaded and follow the instructions on screen to install the downloaded software locally on your computer. 

##### RStudio

* Go to the [RStudio download page](https://www.rstudio.com/products/rstudio/download/#download) and identify the version for your operating system. 
* Under Installers select RStudio Desktop 2022.02.3+492 (**Expected version for Fall 2022**) - Windows Vista/7/8/10 
* Follow the on-screen instructions to download the software and install it on your local machine
* Once it’s installed, open RStudio to make sure it works and you don’t get any error messages.

#### macOS

You will need to download R & RStudio separtely. 

* Download R from the [CRAN website](http://cran.r-project.org/bin/macosx/)
* Select the .pkg file for the latest R version
* Double click on the downloaded file to install R
* It is also a good idea to install [XQuartz](https://www.xquartz.org/) (needed by some packages)
* Go to the [RStudio download page](https://www.rstudio.com/products/rstudio/download/#download)
* Under Installers select RStudio Desktop 2022.02.3+492 (**Expected version for Fall 2022**) - Mac OS X 10.6+ (64-bit) 
* Double click the file to install RStudio
* Once it’s installed, open RStudio to make sure it works and you don’t get any error messages.

#### Linux

* Follow the instructions for your distribution from [CRAN](https://cloud.r-project.org/bin/linux), they provide information to get the most recent version of R for common distributions. For most distributions, you could use your package manager (e.g., for Debian/Ubuntu run `sudo apt-get install r-base`, and for Fedora `sudo yum install R`), but we don’t recommend this approach as the versions provided by this are usually out of date. In any case, make sure you have at least R 4.1.1.
* Go to the [RStudio download page](https://www.rstudio.com/products/rstudio/download/#download)
* Under Installers select the version that matches your distribution, and install it with your preferred method (e.g., with Debian/Ubuntu sudo dpkg -i rstudio-x.yy.zzz-amd64.deb at the terminal).
* Once it’s installed, open RStudio to make sure it works and you don’t get any error messages