----
output:
  pdf_document: default
  html_document: default
---
# Reading and Writing Files in R 
**Author:** Cole Brookson
**Date:** 13 June 2022

Quickly after beginning to use R, as a biologist it is likely you will want to analyze some data. These data will be often stored as external files in your computer, with the most common data file types being Excel Spreadsheet files (<code>.xls(x)</code>), Comma Separated Value files (<code>.csv</code>), or Plain Text (<code>.txt</code>) files.

Since it is best practice to <strong>never</strong> directly edit your raw data files (because what if you need to go back to the original version!?), a common workflow is to:

1. *Read your data into R *`

2. Perform some kind of analysis, creating new data objects, figures, or outputs, then 

3. *Write out those data objects/figures/outputs to your computer for later use*

Steps 1 & 3 will be covered here. 

There are, as there are with all things programming, multiple ways to perform these tasks in both base R and via packages. 

## Reading Files 

When reading in a new file, after manually checking it and ensuring it is formatted in a readable way, note the path in your computer where the file is present. <strong>NOTE</strong> see section on workflow and the <code>here</code> package. 

### Comma-Separated Value `.csv` Files    

This is the recommended file type for reading data into R as it is flexible and easily transferred directly into a dataframe. 

We can read in the file by assinging it directly to an object.

**Base R**
<!--begin.rcode
data <- read.csv("/path/to/file/file-name.csv", header = TRUE)
end.rcode-->

Here the first argument in the `read.csv()` function is the path pointing to the file in your computer. The second argument specifies `header = TRUE` which tells R that the first row of the `.csv` file will be the column names, not part of the data themselves. 

**Tidyverse**

<!--begin.rcode
data <- readr::read_csv("/path/to/file/file-name.csv")
end.rcode-->

### Excel Sheets `.xls(x)`

The best way to read in an excel sheet into R with with the `readxl` package. Almost identical to above: 

<!--begin.rcode
data <- readxl::read_xls("/path/to/file/file-name.csv", sheet = "SHEETNAME")
end.rcode-->

Here, the path argument is identical above, but the `sheet =` argument is an optional argument that you can pass the name of a particular sheet in the file if you only want to read in one sheet out of many. 

### Plain Text `.txt`

Reading a text file is similar to the approaches to a csv file: 

**Base R**

<!--begin.rcode
data <- read.delim("/path/to/file/file-name.csv")
end.rcode-->

This above option assumes that the file it tab-delimited. 

**Tidyverse**

<!--begin.rcode
data <- readr::read_tsv("/path/to/file/file-name.csv")
end.rcode-->

## Writing Files

Writing files is nearly identical to reading files. 

### Comma-Separated Value `.csv` Files 

**core R**

<!--begin.rcode
write.csv(data_object, "/path/to/new/file/file-name.csv")
end.rcode-->

**Tidyverse**
<!--begin.rcode
readr::write_csv(data_object, "/path/to/new/file/file-name.csv")
end.rcode-->

### Excel Sheets `.xls(x)`

Writing a file to an excel sheet is slightly unusual and wouldn't be recommended (<code>.csv</code> files are always better), but if you need to, there exists a number of packages to assist, the easiest of which being <code>writexl</code>.

<!--begin.rcode
library(writexl)
writexl::write_xlsx(data_object, "/path/to/new/file/file-name.xlsx")
end.rcode-->

### Plain Text `.txt`

**core R** 

<!--begin.rcode
write.table(data_object, "/path/to/new/file/file-name.txt")
end.rcode-->

**Tidyverse**

<!--begin.rcode
readr::write_delim(data_object, "/path/to/new/file/file-name.txt")
end.rcode-->

## Writing Figures

It is common to create a figure in R and want to save it to the local machine. If you are plotting in <code>ggplot2</code>, then there are specific functions for those objects, but if you are plotting in base R, you will use built-in functions to save as whatever file type you want. 

Using the example built-in dataset <code>airquality</code>, we can make an example plot to save. 

### Saving an image created in base R 

<!--begin.rcode
plot(x = airquality$Day, y = airquality$Temp, col = "red")
end.rcode-->
If this is the plot we wish to save, we can save it as any common figure file type (e.g. <code>.png</code>, <code>.jpg</code>, <code>.tif</code>, <code>.pdf</code> etc.)

<!--begin.rcode
# first use the command for the file type 
png(file="/path/to/plot/saving_plot.png")
# then we create the plot
hist(Temperature, col="darkgreen")
# this command saves the file and closes the connection to the file
dev.off()
end.rcode-->

### Saving a `ggplot2` object

It is best to use the let of functions from `ggplot2` to save these plots. 

<!--begin.rcode
ggplot2::ggsave("/path/to/plot/saving_plot.png",
                plot_object)
end.rcode-->

Note here that we can change the type of file that gets saved by simply changing the extension on the file name. 
